# Generated by Django 4.0 on 2025-02-03 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_shoes_category_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoes_cart',
            name='size',
            field=models.CharField(default=9, max_length=50),
        ),
    ]
